### ISSUE TITLE
Not a lab

### ISSUE THREAD

**Issue by rockychiang** [learn-co-curriculum/js-dom-and-events-css-libraries-lab#1]
This lesson is showing up as a normal lesson and not a lab (no test or submission required).

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @rockychiang.

We are in the process of updating our JavaScript materials and have documented this as a known issue. This isssue will be resolved in an upcoming version update. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
